version: '3.8'

services:
  chat-app-web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - chat-app-db

  chat-app-db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_chat_app_data:/var/lib/postgresql/data

volumes:
  postgres_chat_app_data:
