services:
  nginx:
    container_name: nginx-chat-app
    image: nginx:1.25.4
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/src/app/static
    depends_on:
      - chat-app-web
  chat-app-web:
    container_name: chat-app
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./logs:/var/log
    depends_on:
      - chat-app-db
      - redis
  chat-app-db:
    container_name: postgres-chat-app
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_chat_app_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    container_name: redis-chat-app
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_chat_app_data:
  redis_data:
