version: '3.8'

services:
  nginx:
    container_name: nginx-chat-app
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chat-app-web
  chat-app-web:
    container_name: chat-app
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - chat-app-db

  chat-app-db:
    container_name: postgres-chat-app
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_chat_app_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_chat_app_data:
