"""Add requester_id and receiver_id

Revision ID: a182f53392c3
Revises: b7575a33ab3d
Create Date: 2023-12-26 09:58:13.753392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a182f53392c3'
down_revision = 'b7575a33ab3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('friendship_friend_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('friendship_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['requester_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('friend_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friend_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('friendship_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('friendship_friend_id_fkey', 'user', ['friend_id'], ['id'])
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('requester_id')

    # ### end Alembic commands ###
