"""Add timestamp to Messege

Revision ID: b60b4476f7ae
Revises: b7575a33ab3d
Create Date: 2023-12-23 11:57:03.916646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60b4476f7ae'
down_revision = 'b7575a33ab3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
